vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
                # alias qui nous permet d'accéder à nos images depuis le navigateur
                uri_prefix: /uploads/series/posters
                # Chemin vers le dossier de stockage
                upload_destination: '%upload_directory_poster%'

        image_file:
                # alias qui nous permet d'accéder à nos images depuis le navigateur
                uri_prefix: /uploads/series/images
                # Chemin vers le dossier de stockage
                upload_destination: '%upload_directory_image%'
